title: Amyah Brown
remote_theme: abhinavs/moonwalk
description: 
  Hi! Welcome to my portfolio! I'm Amyah, a teenage self-taught programmer who wants to display their work. 
  My main skills and interests relate to Python, but I never let that stop me from implementing any idea I have.
  

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: true # if appearance can be switched by user
  back_home_text: "home.." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description
  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  #show_copyright: true # show copyright notice in footer
  # following keys are using to create home layout
  show_projects: true # show projects as cards, add in _data/home.yml
