title: Amyah Brown
remote_theme: abhinavs/moonwalk
description: 
  Hi! Welcome to my portfolio! I'm Amyah, a teenage self-taught programmer who wants to displayer their work. 
  My main skils and interests relate to Python, but I never let that stop me from implementing any idea I have.
  

